apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: node-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 # Replace with your app's port

---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
spec:
  selector:
    app: node-frontend
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose
      targetPort: 80  # The port inside the container that the app is listening on
  type: ClusterIP  # Use 'NodePort' if you want to expose it externally

