apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
      - name: spring-backend
        image: spring-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # Replace with your app's port
        env:
          - name: SA_LOGIC_API_URL
            value: "http://python-services:80"


---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose
      targetPort: 8080  # The port inside the container that the app is listening on
  type: ClusterIP  # Use 'NodePort' if you want to expose it externally

