name: Build and push python app 
on: 
  push: 
    branches: [main] 
    
permissions: 
  contents: read 

jobs: 
  Build-python-app: 
    name: build-pthon-app
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: 'python-service'
      PROJECT_ID: 'my-learning-project-450811' 


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{env.PROJECT_ID}}
        service_account_key: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build Docker Image
      run: |
        cd python-services
        docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker gcr.io --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
       GIT_TAG: v1
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
        docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest